future: true
lsi: true
pygments: true
permalink: pretty
paginate: 10
paginate_path: /page:num
prose:
  rooturl: '_posts'
  siteurl: 'http://andreasmcdermott.com/'
  media: 'assets'
  metadata: 
    _posts: 
      - name: "layout"
        field:
          element: "hidden"
          value: "post"
      - name: "categories"
        field:
          element: "select"
          label: "Category"
          options: 
            - name: "Web"
              value: "web"
            - name: "Games"
              value: "games"
            - name: "Website"
              value: "website"
      - name: "tags"
        field:
          element: "multiselect"
          label: "Tags"
          alterable: true
          options:
            - name: "Github"
              value: "github"
            - name: "Jekyll"
              value: "jekyll"
            - name: "Disqus"
              value: "disqus"
            - name: "Jam"
              value: "jam"
            - name: "Ludum Dare"
              value: "ludum dare"
            - name: "Js"
              value: "js"
            - name: "Firebase"
              value: "firebase"
            - name: "Prose"
              value: "prose"
            - name: "AngularJs"
              value: "angularjs"
            - name: "EmberJs"
              value: "emberjs"
            - name: "Haxe"
              value: "haxe"
            - name: "OpenFl"
              value: "openfl"
            - name: "Sfml"
              value: "sfml"
            - name: "C#"
              value: "c#"
